name: Master Build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Docker Build
        uses: tradeshift/actions-docker-gcr/build@master
        env:
          IMAGE: tradeshift-base/template_project_name
          GCLOUD_SERVICE_ACCOUNT_KEY: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}

      - name: Docker Push 
        uses: tradeshift/actions-docker-gcr/push@master
        env:
          IMAGE: tradeshift-base/template_project_name
          GCLOUD_SERVICE_ACCOUNT_KEY: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}
