name: Sonarqube scanner

on:
  pull_request:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # get all the history
          ref: ${{ github.event.pull_request.head.sha }}
      - name: SonarQube Scan
        uses: tradeshift/sonarqube-action@master
        env:
          NODE_OPTIONS: "--max-old-space-size=10096"
          CACERT: ${{ secrets.MTLS_CACERT }}
          CERT: ${{ secrets.MTLS_CERT }}
          KEY: ${{ secrets.MTLS_KEY }}
          TOKEN: ${{ secrets.SONAR_TOKEN }}      
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SONAR_HOST: "https://sonar.ts.sv"